# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zenoss/protocols/protobufs/messaging.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zenoss/protocols/protobufs/messaging.proto',
  package='org.zenoss.protobufs.messaging',
  serialized_pb='\n*zenoss/protocols/protobufs/messaging.proto\x12\x1eorg.zenoss.protobufs.messaging\"I\n\nAppMessage\x12\x0c\n\x04uuid\x18\x01 \x02(\t\x12\x14\n\x0c\x63reated_time\x18\x02 \x02(\x04\x12\x0c\n\x04type\x18\x03 \x02(\t*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02')




_APPMESSAGE = _descriptor.Descriptor(
  name='AppMessage',
  full_name='org.zenoss.protobufs.messaging.AppMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='org.zenoss.protobufs.messaging.AppMessage.uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_time', full_name='org.zenoss.protobufs.messaging.AppMessage.created_time', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='org.zenoss.protobufs.messaging.AppMessage.type', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(1000, 536870912), ],
  serialized_start=78,
  serialized_end=151,
)

DESCRIPTOR.message_types_by_name['AppMessage'] = _APPMESSAGE

class AppMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _APPMESSAGE

  # @@protoc_insertion_point(class_scope:org.zenoss.protobufs.messaging.AppMessage)


# @@protoc_insertion_point(module_scope)
