# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zenoss/protocols/protobufs/modelrequest.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zenoss/protocols/protobufs/modelrequest.proto',
  package='org.zenoss.protobufs.modelrequest',
  serialized_pb='\n-zenoss/protocols/protobufs/modelrequest.proto\x12!org.zenoss.protobufs.modelrequest\"j\n\x12VMwareModelRequest\x12\x11\n\tcollector\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x02(\x04\x12\x10\n\x08\x65ndpoint\x18\x03 \x02(\t\x12\x11\n\thost_refs\x18\x04 \x03(\t*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02')




_VMWAREMODELREQUEST = _descriptor.Descriptor(
  name='VMwareModelRequest',
  full_name='org.zenoss.protobufs.modelrequest.VMwareModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='collector', full_name='org.zenoss.protobufs.modelrequest.VMwareModelRequest.collector', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='org.zenoss.protobufs.modelrequest.VMwareModelRequest.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='endpoint', full_name='org.zenoss.protobufs.modelrequest.VMwareModelRequest.endpoint', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='host_refs', full_name='org.zenoss.protobufs.modelrequest.VMwareModelRequest.host_refs', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(1000, 536870912), ],
  serialized_start=84,
  serialized_end=190,
)

DESCRIPTOR.message_types_by_name['VMwareModelRequest'] = _VMWAREMODELREQUEST

class VMwareModelRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VMWAREMODELREQUEST

  # @@protoc_insertion_point(class_scope:org.zenoss.protobufs.modelrequest.VMwareModelRequest)


# @@protoc_insertion_point(module_scope)
