# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zenoss/protocols/protobufs/model.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zenoss/protocols/protobufs/model.proto',
  package='org.zenoss.protobufs.model',
  serialized_pb='\n&zenoss/protocols/protobufs/model.proto\x12\x1aorg.zenoss.protobufs.model\"<\n\x06\x44\x65vice\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02\"s\n\tComponent\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x32\n\x06\x64\x65vice\x18\x04 \x01(\x0b\x32\".org.zenoss.protobufs.model.Device*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02\"A\n\tOrganizer\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02\"H\n\x07Service\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07impacts\x18\x03 \x03(\t*\x04\x08\x04\x10\x05*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02*I\n\x10ModelElementType\x12\n\n\x06\x44\x45VICE\x10\x01\x12\r\n\tCOMPONENT\x10\x02\x12\x0b\n\x07SERVICE\x10\x03\x12\r\n\tORGANIZER\x10\x04')

_MODELELEMENTTYPE = _descriptor.EnumDescriptor(
  name='ModelElementType',
  full_name='org.zenoss.protobufs.model.ModelElementType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEVICE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPONENT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVICE', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORGANIZER', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=390,
  serialized_end=463,
)

ModelElementType = enum_type_wrapper.EnumTypeWrapper(_MODELELEMENTTYPE)
DEVICE = 1
COMPONENT = 2
SERVICE = 3
ORGANIZER = 4



_DEVICE = _descriptor.Descriptor(
  name='Device',
  full_name='org.zenoss.protobufs.model.Device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='org.zenoss.protobufs.model.Device.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='org.zenoss.protobufs.model.Device.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='org.zenoss.protobufs.model.Device.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(1000, 536870912), ],
  serialized_start=70,
  serialized_end=130,
)


_COMPONENT = _descriptor.Descriptor(
  name='Component',
  full_name='org.zenoss.protobufs.model.Component',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='org.zenoss.protobufs.model.Component.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='org.zenoss.protobufs.model.Component.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='org.zenoss.protobufs.model.Component.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device', full_name='org.zenoss.protobufs.model.Component.device', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(1000, 536870912), ],
  serialized_start=132,
  serialized_end=247,
)


_ORGANIZER = _descriptor.Descriptor(
  name='Organizer',
  full_name='org.zenoss.protobufs.model.Organizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='org.zenoss.protobufs.model.Organizer.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='org.zenoss.protobufs.model.Organizer.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='org.zenoss.protobufs.model.Organizer.path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(1000, 536870912), ],
  serialized_start=249,
  serialized_end=314,
)


_SERVICE = _descriptor.Descriptor(
  name='Service',
  full_name='org.zenoss.protobufs.model.Service',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='org.zenoss.protobufs.model.Service.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='org.zenoss.protobufs.model.Service.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='impacts', full_name='org.zenoss.protobufs.model.Service.impacts', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(4, 5), (1000, 536870912), ],
  serialized_start=316,
  serialized_end=388,
)

_COMPONENT.fields_by_name['device'].message_type = _DEVICE
DESCRIPTOR.message_types_by_name['Device'] = _DEVICE
DESCRIPTOR.message_types_by_name['Component'] = _COMPONENT
DESCRIPTOR.message_types_by_name['Organizer'] = _ORGANIZER
DESCRIPTOR.message_types_by_name['Service'] = _SERVICE

class Device(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEVICE

  # @@protoc_insertion_point(class_scope:org.zenoss.protobufs.model.Device)

class Component(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMPONENT

  # @@protoc_insertion_point(class_scope:org.zenoss.protobufs.model.Component)

class Organizer(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ORGANIZER

  # @@protoc_insertion_point(class_scope:org.zenoss.protobufs.model.Organizer)

class Service(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVICE

  # @@protoc_insertion_point(class_scope:org.zenoss.protobufs.model.Service)


# @@protoc_insertion_point(module_scope)
