# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zenoss/protocols/protobufs/rpc.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zenoss/protocols/protobufs/rpc.proto',
  package='org.zenoss.protobufs.rpc',
  serialized_pb='\n$zenoss/protocols/protobufs/rpc.proto\x12\x18org.zenoss.protobufs.rpc\"\xbe\x01\n\nRpcRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12H\n\x08requests\x18\x02 \x03(\x0b\x32\x36.org.zenoss.protobufs.rpc.RpcRequest.RpcRequestPayload\x1aO\n\x11RpcRequestPayload\x12\x14\n\x0cservice_name\x18\x01 \x02(\t\x12\x13\n\x0bmethod_name\x18\x02 \x02(\t\x12\x0f\n\x07request\x18\x03 \x02(\x0c*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02\"\xcc\x01\n\x0bRpcResponse\x12\n\n\x02id\x18\x01 \x02(\x05\x12K\n\tresponses\x18\x02 \x03(\x0b\x32\x38.org.zenoss.protobufs.rpc.RpcResponse.RpcResponsePayload\x1aY\n\x12RpcResponsePayload\x12\x10\n\x08response\x18\x01 \x01(\x0c\x12\x31\n\x05\x65rror\x18\x02 \x01(\x0b\x32\".org.zenoss.protobufs.rpc.RpcError*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02\"\xdd\x02\n\x08RpcError\x12\x43\n\nerror_code\x18\x01 \x02(\x0e\x32/.org.zenoss.protobufs.rpc.RpcError.RpcErrorCode\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x17\n\x0f\x65xception_class\x18\x03 \x01(\t\x12\x13\n\x0bstack_trace\x18\x04 \x01(\t\x12\x1a\n\x12service_error_code\x18\x05 \x01(\x05\"\x9f\x01\n\x0cRpcErrorCode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x1b\n\x17INVALID_PROTOCOL_BUFFER\x10\x01\x12\x13\n\x0fUNKNOWN_SERVICE\x10\x02\x12\x12\n\x0eUNKNOWN_METHOD\x10\x03\x12\x13\n\x0fINVALID_REQUEST\x10\x04\x12\x14\n\x10INVALID_RESPONSE\x10\x05\x12\x11\n\rSERVICE_ERROR\x10\x06*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02')



_RPCERROR_RPCERRORCODE = _descriptor.EnumDescriptor(
  name='RpcErrorCode',
  full_name='org.zenoss.protobufs.rpc.RpcError.RpcErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_PROTOCOL_BUFFER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_SERVICE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_METHOD', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_REQUEST', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_RESPONSE', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVICE_ERROR', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=646,
  serialized_end=805,
)


_RPCREQUEST_RPCREQUESTPAYLOAD = _descriptor.Descriptor(
  name='RpcRequestPayload',
  full_name='org.zenoss.protobufs.rpc.RpcRequest.RpcRequestPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='org.zenoss.protobufs.rpc.RpcRequest.RpcRequestPayload.service_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='method_name', full_name='org.zenoss.protobufs.rpc.RpcRequest.RpcRequestPayload.method_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request', full_name='org.zenoss.protobufs.rpc.RpcRequest.RpcRequestPayload.request', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=167,
  serialized_end=246,
)

_RPCREQUEST = _descriptor.Descriptor(
  name='RpcRequest',
  full_name='org.zenoss.protobufs.rpc.RpcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.zenoss.protobufs.rpc.RpcRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requests', full_name='org.zenoss.protobufs.rpc.RpcRequest.requests', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RPCREQUEST_RPCREQUESTPAYLOAD, ],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(1000, 536870912), ],
  serialized_start=67,
  serialized_end=257,
)


_RPCRESPONSE_RPCRESPONSEPAYLOAD = _descriptor.Descriptor(
  name='RpcResponsePayload',
  full_name='org.zenoss.protobufs.rpc.RpcResponse.RpcResponsePayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='org.zenoss.protobufs.rpc.RpcResponse.RpcResponsePayload.response', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='org.zenoss.protobufs.rpc.RpcResponse.RpcResponsePayload.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=364,
  serialized_end=453,
)

_RPCRESPONSE = _descriptor.Descriptor(
  name='RpcResponse',
  full_name='org.zenoss.protobufs.rpc.RpcResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.zenoss.protobufs.rpc.RpcResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responses', full_name='org.zenoss.protobufs.rpc.RpcResponse.responses', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RPCRESPONSE_RPCRESPONSEPAYLOAD, ],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(1000, 536870912), ],
  serialized_start=260,
  serialized_end=464,
)


_RPCERROR = _descriptor.Descriptor(
  name='RpcError',
  full_name='org.zenoss.protobufs.rpc.RpcError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='org.zenoss.protobufs.rpc.RpcError.error_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='org.zenoss.protobufs.rpc.RpcError.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exception_class', full_name='org.zenoss.protobufs.rpc.RpcError.exception_class', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stack_trace', full_name='org.zenoss.protobufs.rpc.RpcError.stack_trace', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='service_error_code', full_name='org.zenoss.protobufs.rpc.RpcError.service_error_code', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RPCERROR_RPCERRORCODE,
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(1000, 536870912), ],
  serialized_start=467,
  serialized_end=816,
)

_RPCREQUEST_RPCREQUESTPAYLOAD.containing_type = _RPCREQUEST;
_RPCREQUEST.fields_by_name['requests'].message_type = _RPCREQUEST_RPCREQUESTPAYLOAD
_RPCRESPONSE_RPCRESPONSEPAYLOAD.fields_by_name['error'].message_type = _RPCERROR
_RPCRESPONSE_RPCRESPONSEPAYLOAD.containing_type = _RPCRESPONSE;
_RPCRESPONSE.fields_by_name['responses'].message_type = _RPCRESPONSE_RPCRESPONSEPAYLOAD
_RPCERROR.fields_by_name['error_code'].enum_type = _RPCERROR_RPCERRORCODE
_RPCERROR_RPCERRORCODE.containing_type = _RPCERROR;
DESCRIPTOR.message_types_by_name['RpcRequest'] = _RPCREQUEST
DESCRIPTOR.message_types_by_name['RpcResponse'] = _RPCRESPONSE
DESCRIPTOR.message_types_by_name['RpcError'] = _RPCERROR

class RpcRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class RpcRequestPayload(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _RPCREQUEST_RPCREQUESTPAYLOAD

    # @@protoc_insertion_point(class_scope:org.zenoss.protobufs.rpc.RpcRequest.RpcRequestPayload)
  DESCRIPTOR = _RPCREQUEST

  # @@protoc_insertion_point(class_scope:org.zenoss.protobufs.rpc.RpcRequest)

class RpcResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class RpcResponsePayload(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _RPCRESPONSE_RPCRESPONSEPAYLOAD

    # @@protoc_insertion_point(class_scope:org.zenoss.protobufs.rpc.RpcResponse.RpcResponsePayload)
  DESCRIPTOR = _RPCRESPONSE

  # @@protoc_insertion_point(class_scope:org.zenoss.protobufs.rpc.RpcResponse)

class RpcError(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RPCERROR

  # @@protoc_insertion_point(class_scope:org.zenoss.protobufs.rpc.RpcError)


# @@protoc_insertion_point(module_scope)
