# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zenoss/protocols/protobufs/util.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zenoss/protocols/protobufs/util.proto',
  package='org.zenoss.protobufs.util',
  serialized_pb='\n%zenoss/protocols/protobufs/util.proto\x12\x19org.zenoss.protobufs.util\"6\n\x0eTimestampRange\x12\x12\n\nstart_time\x18\x01 \x01(\x04\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x04\"\xa0\x02\n\x0eScheduleWindow\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x03 \x01(\x08\x12\x14\n\x0c\x63reated_time\x18\x04 \x01(\x04\x12\x18\n\x10\x64uration_seconds\x18\x05 \x01(\x05\x12\x44\n\x06repeat\x18\x06 \x01(\x0e\x32\x34.org.zenoss.protobufs.util.ScheduleWindow.RepeatType\"`\n\nRepeatType\x12\t\n\x05NEVER\x10\x00\x12\t\n\x05\x44\x41ILY\x10\x01\x12\x11\n\rEVERY_WEEKDAY\x10\x02\x12\n\n\x06WEEKLY\x10\x03\x12\x0b\n\x07MONTHLY\x10\x04\x12\x10\n\x0c\x46IRST_SUNDAY\x10\x05*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02\"O\n\x11ScheduleWindowSet\x12:\n\x07windows\x18\x01 \x03(\x0b\x32).org.zenoss.protobufs.util.ScheduleWindow\"2\n\x08Property\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02')



_SCHEDULEWINDOW_REPEATTYPE = _descriptor.EnumDescriptor(
  name='RepeatType',
  full_name='org.zenoss.protobufs.util.ScheduleWindow.RepeatType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NEVER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DAILY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVERY_WEEKDAY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEEKLY', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MONTHLY', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIRST_SUNDAY', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=306,
  serialized_end=402,
)


_TIMESTAMPRANGE = _descriptor.Descriptor(
  name='TimestampRange',
  full_name='org.zenoss.protobufs.util.TimestampRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time', full_name='org.zenoss.protobufs.util.TimestampRange.start_time', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='org.zenoss.protobufs.util.TimestampRange.end_time', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=68,
  serialized_end=122,
)


_SCHEDULEWINDOW = _descriptor.Descriptor(
  name='ScheduleWindow',
  full_name='org.zenoss.protobufs.util.ScheduleWindow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='org.zenoss.protobufs.util.ScheduleWindow.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='org.zenoss.protobufs.util.ScheduleWindow.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='org.zenoss.protobufs.util.ScheduleWindow.enabled', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_time', full_name='org.zenoss.protobufs.util.ScheduleWindow.created_time', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration_seconds', full_name='org.zenoss.protobufs.util.ScheduleWindow.duration_seconds', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='repeat', full_name='org.zenoss.protobufs.util.ScheduleWindow.repeat', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SCHEDULEWINDOW_REPEATTYPE,
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(1000, 536870912), ],
  serialized_start=125,
  serialized_end=413,
)


_SCHEDULEWINDOWSET = _descriptor.Descriptor(
  name='ScheduleWindowSet',
  full_name='org.zenoss.protobufs.util.ScheduleWindowSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='windows', full_name='org.zenoss.protobufs.util.ScheduleWindowSet.windows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=415,
  serialized_end=494,
)


_PROPERTY = _descriptor.Descriptor(
  name='Property',
  full_name='org.zenoss.protobufs.util.Property',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='org.zenoss.protobufs.util.Property.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='org.zenoss.protobufs.util.Property.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(1000, 536870912), ],
  serialized_start=496,
  serialized_end=546,
)

_SCHEDULEWINDOW.fields_by_name['repeat'].enum_type = _SCHEDULEWINDOW_REPEATTYPE
_SCHEDULEWINDOW_REPEATTYPE.containing_type = _SCHEDULEWINDOW;
_SCHEDULEWINDOWSET.fields_by_name['windows'].message_type = _SCHEDULEWINDOW
DESCRIPTOR.message_types_by_name['TimestampRange'] = _TIMESTAMPRANGE
DESCRIPTOR.message_types_by_name['ScheduleWindow'] = _SCHEDULEWINDOW
DESCRIPTOR.message_types_by_name['ScheduleWindowSet'] = _SCHEDULEWINDOWSET
DESCRIPTOR.message_types_by_name['Property'] = _PROPERTY

class TimestampRange(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TIMESTAMPRANGE

  # @@protoc_insertion_point(class_scope:org.zenoss.protobufs.util.TimestampRange)

class ScheduleWindow(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SCHEDULEWINDOW

  # @@protoc_insertion_point(class_scope:org.zenoss.protobufs.util.ScheduleWindow)

class ScheduleWindowSet(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SCHEDULEWINDOWSET

  # @@protoc_insertion_point(class_scope:org.zenoss.protobufs.util.ScheduleWindowSet)

class Property(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROPERTY

  # @@protoc_insertion_point(class_scope:org.zenoss.protobufs.util.Property)


# @@protoc_insertion_point(module_scope)
