#!/usr/local/zenoss/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'Zope2==2.13.13','console_scripts','mkzopeinstance'
__requires__ = 'Zope2==2.13.13'
import sys
from pkg_resources import load_entry_point

sys.exit(
   load_entry_point('Zope2==2.13.13', 'console_scripts', 'mkzopeinstance')()
)
